import os
import sys
import argparse
import requests
import glob
import shutil
import argparse
import requests
import glob
import shutil

def main():
    parser = argparse.ArgumentParser(description="MathTutor-PaddleOCR: Distorted Image Math Solver")
    parser.add_argument("image_path", help="Local path to the math image.")
    parser.add_argument("--task", default="Formula Recognition:", choices=["Formula Recognition:", "OCR:"])
    parser.add_argument("--ollama-model", default="llama3.2:1b", help="Ollama model name.")
    parser.add_argument("--ollama-url", default="http://localhost:11434", help="Ollama API base URL.")
    args = parser.parse_args()

    # 1. Validation
    if not os.path.isfile(args.image_path):
        print(f"[Error] Image file not found: {args.image_path}")
        sys.exit(1)

    # 2. Check Ollama
    print("[1/3] Checking Ollama service...")
    try:
        requests.get(args.ollama_url, timeout=2)
    except requests.RequestException:
        print("[Error] Failed to connect to Ollama server. Is it running?")
        sys.exit(1)

    # 3. Load PaddleOCR-VL and run prediction
    print("[2/3] Initializing and running SOTA PaddleOCR-VL...")
    try:
        from paddleocr import PaddleOCRVL
        # Try version v1.6, fallback to v1.5 if needed
        try:
            pipeline = PaddleOCRVL(pipeline_version="v1.6")
        except ValueError:
            pipeline = PaddleOCRVL(pipeline_version="v1.5")
            
        output = pipeline.predict(args.image_path)
    except Exception as e:
        import traceback
        traceback.print_exc()
        print(f"[Error] PaddleOCR-VL execution failed: {e}")
        sys.exit(1)

    if not output:
        print("[Error] No output generated by PaddleOCR-VL.")
        sys.exit(1)

    res = output[0]
    extracted_text = ""
    if hasattr(res, "markdown"):
        extracted_text = res.markdown
    elif isinstance(res, dict) and "markdown" in res:
        extracted_text = res["markdown"]
    
    # Fallback: write to temp folder and read the saved markdown file
    if not extracted_text:
        temp_dir = "temp_pocr_out"
        os.makedirs(temp_dir, exist_ok=True)
        try:
            res.save_to_markdown(temp_dir)
            md_files = glob.glob(os.path.join(temp_dir, "*.md"))
            if md_files:
                with open(md_files[0], "r", encoding="utf-8") as f:
                    extracted_text = f.read().strip()
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)

    if not extracted_text:
        print("[Error] No text/formula could be extracted.")
        sys.exit(1)

    print(f"\nRAW EXTRACTION:\n{extracted_text}\n" + "="*50)

    # 4. Solve via Ollama
    print(f"[3/3] Sending formula to Ollama model '{args.ollama_model}'...")
    payload = {
        "model": args.ollama_model,
        "prompt": extracted_text,
        "system": "You are a math tutor. Solve the following extracted formula step-by-step. Keep it brief. Do not use <think> tags. Just output the solution.",
        "stream": False
    }
    
    try:
        response = requests.post(f"{args.ollama_url.rstrip('/')}/api/generate", json=payload, timeout=30)
        if response.status_code == 200:
            solution = response.json().get("response", "").strip()
            print(f"\nOLLAMA TUTOR SOLUTION:\n{solution}\n" + "="*50)
            
            # Save output as md
            base, _ = os.path.splitext(args.image_path)
            output_md_path = f"{base}_output.md"
            with open(output_md_path, "w", encoding="utf-8") as f:
                f.write(f"# MathTutor-PaddleOCR Output\n\n- Image: `{args.image_path}`\n\n## Extraction\n$$\n{extracted_text}\n$$\n\n## Solution\n{solution}\n")
            print(f"[Info] Saved output to: {output_md_path}\n")
        else:
            print(f"[Error] Ollama returned status code: {response.status_code}")
    except Exception as e:
        print(f"[Error] Ollama generation failed: {e}")

if __name__ == "__main__":
    main()
